# Generated by Django 5.0.4 on 2024-11-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_recycleform_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='organisation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
